// Generated by scripts/generate-cli-capabilities.ts. Do not edit manually.
export const CLI_CAPABILITIES_RUNTIME = {
  "schema_version": 1,
  "commands": {
    "context.get": {
      "command": "remi context",
      "auth": [
        "human",
        "task",
        "daemon",
        "share"
      ],
      "capability": "context.read",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    }
  }
} as const;
