// Generated by scripts/generate-cli-capabilities.ts. Do not edit manually.
export const CLI_CAPABILITIES_RUNTIME = {
  "schema_version": 1,
  "commands": {
    "context.get": {
      "command": "remi context",
      "auth": [
        "human",
        "task",
        "daemon",
        "share"
      ],
      "capability": "context.read",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "workspace.list": {
      "command": "remi workspace list",
      "auth": [
        "human"
      ],
      "capability": "workspace.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "workspace.get": {
      "command": "remi workspace get",
      "auth": [
        "human"
      ],
      "capability": "workspace.get",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "workspace.create": {
      "command": "remi workspace create",
      "auth": [
        "human"
      ],
      "capability": "workspace.create",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "workspace.update": {
      "command": "remi workspace update",
      "auth": [
        "human"
      ],
      "capability": "workspace.update",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "workspace.delete": {
      "command": "remi workspace delete",
      "auth": [
        "human"
      ],
      "capability": "workspace.delete",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "workspace.leave": {
      "command": "remi workspace leave",
      "auth": [
        "human"
      ],
      "capability": "workspace.leave",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "workspace.env.get": {
      "command": "remi workspace env get",
      "auth": [
        "human"
      ],
      "capability": "workspace.env.get",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "workspace.env.update": {
      "command": "remi workspace env update",
      "auth": [
        "human"
      ],
      "capability": "workspace.env.update",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "workspace.ssh-mesh.get": {
      "command": "remi workspace ssh-mesh get",
      "auth": [
        "human"
      ],
      "capability": "workspace.ssh-mesh.get",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "workspace.ssh-mesh.update": {
      "command": "remi workspace ssh-mesh update",
      "auth": [
        "human"
      ],
      "capability": "workspace.ssh-mesh.update",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "workspace.ssh-mesh.rotate": {
      "command": "remi workspace ssh-mesh rotate",
      "auth": [
        "human"
      ],
      "capability": "workspace.ssh-mesh.rotate",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "workspace.ssh-mesh.test": {
      "command": "remi workspace ssh-mesh test",
      "auth": [
        "human"
      ],
      "capability": "workspace.ssh-mesh.test",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "workspace.relay.get": {
      "command": "remi workspace relay get",
      "auth": [
        "human"
      ],
      "capability": "workspace.relay.get",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "workspace.relay.discovery": {
      "command": "remi workspace relay discovery",
      "auth": [
        "human"
      ],
      "capability": "workspace.relay.discovery",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "workspace.relay.update": {
      "command": "remi workspace relay update",
      "auth": [
        "human"
      ],
      "capability": "workspace.relay.update",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "workspace.relay.reveal": {
      "command": "remi workspace relay reveal",
      "auth": [
        "human"
      ],
      "capability": "workspace.relay.reveal",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "member.list": {
      "command": "remi member list",
      "auth": [
        "human"
      ],
      "capability": "member.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "member.get": {
      "command": "remi member get",
      "auth": [
        "human"
      ],
      "capability": "member.get",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "member.create": {
      "command": "remi member create",
      "auth": [
        "human"
      ],
      "capability": "member.create",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "member.update": {
      "command": "remi member update",
      "auth": [
        "human"
      ],
      "capability": "member.update",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "member.delete": {
      "command": "remi member delete",
      "auth": [
        "human"
      ],
      "capability": "member.delete",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "member.onboarding.update": {
      "command": "remi member onboarding update",
      "auth": [
        "human"
      ],
      "capability": "member.onboarding.update",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "member.onboarding.complete": {
      "command": "remi member onboarding complete",
      "auth": [
        "human"
      ],
      "capability": "member.onboarding.complete",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "member.onboarding.cloud-waitlist": {
      "command": "remi member onboarding cloud-waitlist",
      "auth": [
        "human"
      ],
      "capability": "member.onboarding.cloud-waitlist",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "member.onboarding.runtime-bootstrap": {
      "command": "remi member onboarding runtime-bootstrap",
      "auth": [
        "human"
      ],
      "capability": "member.onboarding.runtime-bootstrap",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "member.onboarding.no-runtime-bootstrap": {
      "command": "remi member onboarding no-runtime-bootstrap",
      "auth": [
        "human"
      ],
      "capability": "member.onboarding.no-runtime-bootstrap",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "invite.list": {
      "command": "remi invite list",
      "auth": [
        "human"
      ],
      "capability": "invite.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "invite.get": {
      "command": "remi invite get",
      "auth": [
        "human"
      ],
      "capability": "invite.get",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "invite.create": {
      "command": "remi invite create",
      "auth": [
        "human"
      ],
      "capability": "invite.create",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "invite.accept": {
      "command": "remi invite accept",
      "auth": [
        "human"
      ],
      "capability": "invite.accept",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "invite.decline": {
      "command": "remi invite decline",
      "auth": [
        "human"
      ],
      "capability": "invite.decline",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "invite.revoke": {
      "command": "remi invite revoke",
      "auth": [
        "human"
      ],
      "capability": "invite.revoke",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "token.list": {
      "command": "remi token list",
      "auth": [
        "human"
      ],
      "capability": "token.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "token.create": {
      "command": "remi token create",
      "auth": [
        "human"
      ],
      "capability": "token.create",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "token.renew": {
      "command": "remi token renew",
      "auth": [
        "human"
      ],
      "capability": "token.renew",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "token.delete": {
      "command": "remi token delete",
      "auth": [
        "human"
      ],
      "capability": "token.delete",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "project.list": {
      "command": "remi project list",
      "auth": [
        "human",
        "task"
      ],
      "capability": "project.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "project.search": {
      "command": "remi project search",
      "auth": [
        "human",
        "task"
      ],
      "capability": "project.search",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "project.get": {
      "command": "remi project get",
      "auth": [
        "human",
        "task"
      ],
      "capability": "project.get",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "project.defaults": {
      "command": "remi project defaults",
      "auth": [
        "human",
        "task"
      ],
      "capability": "project.defaults",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "project.create": {
      "command": "remi project create",
      "auth": [
        "human"
      ],
      "capability": "project.create",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "project.update": {
      "command": "remi project update",
      "auth": [
        "human"
      ],
      "capability": "project.update",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "project.archive": {
      "command": "remi project archive",
      "auth": [
        "human"
      ],
      "capability": "project.archive",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "project.restore": {
      "command": "remi project restore",
      "auth": [
        "human"
      ],
      "capability": "project.restore",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "project.resource.list": {
      "command": "remi project resource list",
      "auth": [
        "human",
        "task"
      ],
      "capability": "project.resource.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "project.resource.create": {
      "command": "remi project resource create",
      "auth": [
        "human"
      ],
      "capability": "project.resource.create",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "project.resource.update": {
      "command": "remi project resource update",
      "auth": [
        "human"
      ],
      "capability": "project.resource.update",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "project.resource.delete": {
      "command": "remi project resource delete",
      "auth": [
        "human"
      ],
      "capability": "project.resource.delete",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "repo.list": {
      "command": "remi repo list",
      "auth": [
        "human",
        "task"
      ],
      "capability": "repo.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "repo.get": {
      "command": "remi repo get",
      "auth": [
        "human",
        "task"
      ],
      "capability": "repo.get",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "repo.inspect": {
      "command": "remi repo inspect",
      "auth": [
        "human"
      ],
      "capability": "repo.inspect",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "repo.create": {
      "command": "remi repo create",
      "auth": [
        "human"
      ],
      "capability": "repo.create",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "repo.update": {
      "command": "remi repo update",
      "auth": [
        "human"
      ],
      "capability": "repo.update",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "repo.delete": {
      "command": "remi repo delete",
      "auth": [
        "human"
      ],
      "capability": "repo.delete",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "repo.checkout": {
      "command": "remi repo checkout",
      "auth": [
        "human",
        "task"
      ],
      "capability": "repo.checkout",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "memory.list": {
      "command": "remi memory list",
      "auth": [
        "human",
        "task"
      ],
      "capability": "memory.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "memory.search": {
      "command": "remi memory search",
      "auth": [
        "human",
        "task"
      ],
      "capability": "memory.search",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "memory.get": {
      "command": "remi memory get",
      "auth": [
        "human",
        "task"
      ],
      "capability": "memory.get",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "memory.create": {
      "command": "remi memory create",
      "auth": [
        "human",
        "task"
      ],
      "capability": "memory.create",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "memory.update": {
      "command": "remi memory update",
      "auth": [
        "human",
        "task"
      ],
      "capability": "memory.update",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "memory.delete": {
      "command": "remi memory delete",
      "auth": [
        "human",
        "task"
      ],
      "capability": "memory.delete",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "memory.backlinks": {
      "command": "remi memory backlinks",
      "auth": [
        "human",
        "task"
      ],
      "capability": "memory.backlinks",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "wiki.list": {
      "command": "remi wiki list",
      "auth": [
        "human",
        "task"
      ],
      "capability": "wiki.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "wiki.search": {
      "command": "remi wiki search",
      "auth": [
        "human",
        "task"
      ],
      "capability": "wiki.search",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "wiki.get": {
      "command": "remi wiki get",
      "auth": [
        "human",
        "task"
      ],
      "capability": "wiki.get",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "wiki.create": {
      "command": "remi wiki create",
      "auth": [
        "human",
        "task"
      ],
      "capability": "wiki.create",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "wiki.update": {
      "command": "remi wiki update",
      "auth": [
        "human",
        "task"
      ],
      "capability": "wiki.update",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "wiki.delete": {
      "command": "remi wiki delete",
      "auth": [
        "human",
        "task"
      ],
      "capability": "wiki.delete",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "wiki.backlinks": {
      "command": "remi wiki backlinks",
      "auth": [
        "human",
        "task"
      ],
      "capability": "wiki.backlinks",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "wiki.revisions": {
      "command": "remi wiki revisions",
      "auth": [
        "human",
        "task"
      ],
      "capability": "wiki.revisions",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "memory.migration.status": {
      "command": "remi memory migration status",
      "auth": [
        "human"
      ],
      "capability": "memory.migration.status",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "memory.migration.backfill": {
      "command": "remi memory migration backfill",
      "auth": [
        "human"
      ],
      "capability": "memory.migration.backfill",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "memory.migration.verify": {
      "command": "remi memory migration verify",
      "auth": [
        "human"
      ],
      "capability": "memory.migration.verify",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "memory.migration.retry": {
      "command": "remi memory migration retry",
      "auth": [
        "human"
      ],
      "capability": "memory.migration.retry",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "wiki.pull": {
      "command": "remi wiki pull",
      "auth": [
        "human",
        "task"
      ],
      "capability": "wiki.pull",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "wiki.status": {
      "command": "remi wiki status",
      "auth": [
        "human",
        "task"
      ],
      "capability": "wiki.status",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "wiki.diff": {
      "command": "remi wiki diff",
      "auth": [
        "human",
        "task"
      ],
      "capability": "wiki.diff",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "wiki.push": {
      "command": "remi wiki push",
      "auth": [
        "human",
        "task"
      ],
      "capability": "wiki.push",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.list": {
      "command": "remi issue list",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.get": {
      "command": "remi issue get",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.get",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.search": {
      "command": "remi issue search",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.search",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.create": {
      "command": "remi issue create",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.create",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.update": {
      "command": "remi issue update",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.update",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.assign": {
      "command": "remi issue assign",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.assign",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.status": {
      "command": "remi issue status",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.status",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.delete": {
      "command": "remi issue delete",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.delete",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.rerun": {
      "command": "remi issue rerun",
      "auth": [
        "human"
      ],
      "capability": "issue.rerun",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.cancel": {
      "command": "remi issue cancel-task",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.cancel",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.task-runs": {
      "command": "remi issue runs",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.task-runs",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "task.messages": {
      "command": "remi issue run-messages",
      "auth": [
        "human",
        "task"
      ],
      "capability": "task.messages",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "comment.list": {
      "command": "remi comment list",
      "auth": [
        "human",
        "task"
      ],
      "capability": "comment.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "comment.add": {
      "command": "remi comment add",
      "auth": [
        "human",
        "task"
      ],
      "capability": "comment.add",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "comment.update": {
      "command": "remi comment update",
      "auth": [
        "human",
        "task"
      ],
      "capability": "comment.update",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "comment.delete": {
      "command": "remi comment delete",
      "auth": [
        "human",
        "task"
      ],
      "capability": "comment.delete",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "comment.resolve": {
      "command": "remi comment resolve",
      "auth": [
        "human",
        "task"
      ],
      "capability": "comment.resolve",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "comment.unresolve": {
      "command": "remi comment unresolve",
      "auth": [
        "human",
        "task"
      ],
      "capability": "comment.unresolve",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "comment.reaction.list": {
      "command": "remi comment reaction list",
      "auth": [
        "human",
        "task"
      ],
      "capability": "comment.reaction.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "comment.reaction.add": {
      "command": "remi comment reaction add",
      "auth": [
        "human",
        "task"
      ],
      "capability": "comment.reaction.add",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "comment.reaction.remove": {
      "command": "remi comment reaction remove",
      "auth": [
        "human",
        "task"
      ],
      "capability": "comment.reaction.remove",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "comment.attachment.list": {
      "command": "remi comment attachment list",
      "auth": [
        "human",
        "task"
      ],
      "capability": "comment.attachment.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "session.list": {
      "command": "remi session list",
      "auth": [
        "human",
        "task"
      ],
      "capability": "session.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "session.get": {
      "command": "remi session get",
      "auth": [
        "human",
        "task"
      ],
      "capability": "session.get",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "session.create": {
      "command": "remi session create",
      "auth": [
        "human"
      ],
      "capability": "session.create",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "session.update": {
      "command": "remi session update",
      "auth": [
        "human"
      ],
      "capability": "session.update",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "session.participant.list": {
      "command": "remi session participant list",
      "auth": [
        "human",
        "task"
      ],
      "capability": "session.participant.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "session.participant.add": {
      "command": "remi session participant add",
      "auth": [
        "human"
      ],
      "capability": "session.participant.add",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "session.participant.remove": {
      "command": "remi session participant remove",
      "auth": [
        "human"
      ],
      "capability": "session.participant.remove",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "session.event.list": {
      "command": "remi session event list",
      "auth": [
        "human",
        "task"
      ],
      "capability": "session.event.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "session.message.create": {
      "command": "remi session message create",
      "auth": [
        "human",
        "task"
      ],
      "capability": "session.message.create",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "session.task.list": {
      "command": "remi session task list",
      "auth": [
        "human",
        "task"
      ],
      "capability": "session.task.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "session.task.create": {
      "command": "remi session task create",
      "auth": [
        "human",
        "task"
      ],
      "capability": "session.task.create",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "session.result.list": {
      "command": "remi session result list",
      "auth": [
        "human",
        "task"
      ],
      "capability": "session.result.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "session.result.publish": {
      "command": "remi session result publish",
      "auth": [
        "human",
        "task"
      ],
      "capability": "session.result.publish",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "session.archive.list": {
      "command": "remi session archive list",
      "auth": [
        "human"
      ],
      "capability": "session.archive.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "session.archive.status": {
      "command": "remi session archive status",
      "auth": [
        "human"
      ],
      "capability": "session.archive.status",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "session.archive.verify": {
      "command": "remi session archive verify",
      "auth": [
        "human"
      ],
      "capability": "session.archive.verify",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "session.archive.retry": {
      "command": "remi session archive retry",
      "auth": [
        "human"
      ],
      "capability": "session.archive.retry",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "session.config.get": {
      "command": "remi session config get",
      "auth": [
        "human"
      ],
      "capability": "session.config.get",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "session.config.update": {
      "command": "remi session config update",
      "auth": [
        "human"
      ],
      "capability": "session.config.update",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.grouped": {
      "command": "remi issue grouped",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.grouped",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.children": {
      "command": "remi issue children",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.children",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.child-progress": {
      "command": "remi issue child-progress",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.child-progress",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.timeline": {
      "command": "remi issue timeline",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.timeline",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.active-task": {
      "command": "remi issue active-task",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.active-task",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.usage": {
      "command": "remi issue usage",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.usage",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.workspace": {
      "command": "remi issue workspace",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.workspace",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.dependency.list": {
      "command": "remi issue dependency list",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.dependency.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.dependency.add": {
      "command": "remi issue dependency add",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.dependency.add",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.dependency.remove": {
      "command": "remi issue dependency remove",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.dependency.remove",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.reaction.list": {
      "command": "remi issue reaction list",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.reaction.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.reaction.add": {
      "command": "remi issue reaction add",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.reaction.add",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.reaction.remove": {
      "command": "remi issue reaction remove",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.reaction.remove",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.label.list": {
      "command": "remi issue label list",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.label.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.label.add": {
      "command": "remi issue label add",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.label.add",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.label.remove": {
      "command": "remi issue label remove",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.label.remove",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.subscriber.list": {
      "command": "remi issue subscriber list",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.subscriber.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.subscriber.add": {
      "command": "remi issue subscriber add",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.subscriber.add",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.subscriber.remove": {
      "command": "remi issue subscriber remove",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.subscriber.remove",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.metadata.list": {
      "command": "remi issue metadata list",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.metadata.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.metadata.get": {
      "command": "remi issue metadata get",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.metadata.get",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.metadata.set": {
      "command": "remi issue metadata set",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.metadata.set",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.metadata.delete": {
      "command": "remi issue metadata delete",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.metadata.delete",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.attachment.list": {
      "command": "remi issue attachment list",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.attachment.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.attachment.get": {
      "command": "remi issue attachment get",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.attachment.get",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.attachment.download": {
      "command": "remi issue attachment download",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.attachment.download",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.attachment.upload": {
      "command": "remi issue attachment upload",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.attachment.upload",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.attachment.delete": {
      "command": "remi issue attachment delete",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.attachment.delete",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.batch-update": {
      "command": "remi issue batch-update",
      "auth": [
        "human"
      ],
      "capability": "issue.batch-update",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.batch-delete": {
      "command": "remi issue batch-delete",
      "auth": [
        "human"
      ],
      "capability": "issue.batch-delete",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.quick-create": {
      "command": "remi issue quick-create",
      "auth": [
        "human"
      ],
      "capability": "issue.quick-create",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "issue.squad-evaluated": {
      "command": "remi issue squad-evaluated",
      "auth": [
        "human",
        "task"
      ],
      "capability": "issue.squad-evaluated",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "share.get": {
      "command": "remi share get",
      "auth": [
        "human"
      ],
      "capability": "share.get",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "share.create": {
      "command": "remi share create",
      "auth": [
        "human"
      ],
      "capability": "share.create",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "share.extend": {
      "command": "remi share extend",
      "auth": [
        "human"
      ],
      "capability": "share.extend",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "share.delete": {
      "command": "remi share delete",
      "auth": [
        "human"
      ],
      "capability": "share.delete",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "share.view": {
      "command": "remi share view",
      "auth": [
        "human",
        "share"
      ],
      "capability": "share.view",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "label.list": {
      "command": "remi label list",
      "auth": [
        "human",
        "task"
      ],
      "capability": "label.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "label.get": {
      "command": "remi label get",
      "auth": [
        "human",
        "task"
      ],
      "capability": "label.get",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "label.create": {
      "command": "remi label create",
      "auth": [
        "human"
      ],
      "capability": "label.create",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "label.update": {
      "command": "remi label update",
      "auth": [
        "human"
      ],
      "capability": "label.update",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "label.delete": {
      "command": "remi label delete",
      "auth": [
        "human"
      ],
      "capability": "label.delete",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "chat.list": {
      "command": "remi chat list",
      "auth": [
        "human"
      ],
      "capability": "chat.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "chat.get": {
      "command": "remi chat get",
      "auth": [
        "human"
      ],
      "capability": "chat.get",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "chat.create": {
      "command": "remi chat create",
      "auth": [
        "human"
      ],
      "capability": "chat.create",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "chat.update": {
      "command": "remi chat update",
      "auth": [
        "human"
      ],
      "capability": "chat.update",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "chat.delete": {
      "command": "remi chat delete",
      "auth": [
        "human"
      ],
      "capability": "chat.delete",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "chat.message.list": {
      "command": "remi chat message list",
      "auth": [
        "human"
      ],
      "capability": "chat.message.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "chat.message.create": {
      "command": "remi chat message create",
      "auth": [
        "human"
      ],
      "capability": "chat.message.create",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "chat.pending": {
      "command": "remi chat pending",
      "auth": [
        "human"
      ],
      "capability": "chat.pending",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "chat.read": {
      "command": "remi chat read",
      "auth": [
        "human"
      ],
      "capability": "chat.read",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "task.list": {
      "command": "remi task list",
      "auth": [
        "human",
        "task"
      ],
      "capability": "task.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "task.get": {
      "command": "remi task get",
      "auth": [
        "human",
        "task"
      ],
      "capability": "task.get",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "task.create": {
      "command": "remi task create",
      "auth": [
        "human"
      ],
      "capability": "task.create",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "task.cancel": {
      "command": "remi task cancel",
      "auth": [
        "human",
        "task"
      ],
      "capability": "task.cancel",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "task.message.list": {
      "command": "remi task message list",
      "auth": [
        "human",
        "task"
      ],
      "capability": "task.message.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "task.prompt": {
      "command": "remi task prompt",
      "auth": [
        "human",
        "task"
      ],
      "capability": "task.prompt",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "task.request.list": {
      "command": "remi task request list",
      "auth": [
        "human",
        "task"
      ],
      "capability": "task.request.list",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    },
    "task.request.respond": {
      "command": "remi task request respond",
      "auth": [
        "human",
        "task"
      ],
      "capability": "task.request.respond",
      "output": [
        "table",
        "json",
        "jsonl"
      ]
    }
  }
} as const;
