#!/usr/bin/env bun

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { cliCommandInventory } from "../apps/remi/cli/index.js";
import {
  cliCoverageReport,
  cliRuntimeCapabilities,
  type CliCapabilitiesManifest,
  type CliExemptCategory,
  type CliManifestRoute,
  validateCliCapabilities,
} from "./cli-capabilities.js";

const ROOT = resolve(import.meta.dir, "..");
const GOLDEN_PATH = resolve(ROOT, "scripts/api-routes.golden.json");
const MANIFEST_PATH = resolve(ROOT, "cli-capabilities.json");
const RUNTIME_MANIFEST_PATH = resolve(ROOT, "packages/server/src/api/cli-capabilities-generated.ts");
const MAX_PLANNED_ROUTES = 505;

const DOMAINS = [
  "context", "workspace", "member", "invite", "token",
  "project", "repo", "memory", "wiki",
  "issue", "comment", "session", "share", "label", "attachment",
  "chat", "task",
  "agent", "squad", "skill", "plugin",
  "runtime", "daemon", "autopilot", "scm",
  "inbox", "notification", "pin", "dashboard", "platform", "billing", "lark",
];

const DOMAIN_ALIASES: Record<string, string> = {
  "agent-plugins": "plugin",
  "agent-templates": "agent",
  "agent-activity-30d": "dashboard",
  "agent-run-counts": "dashboard",
  "agent-task-snapshot": "dashboard",
  "assignee-frequency": "dashboard",
  agents: "agent",
  attachments: "attachment",
  autopilots: "autopilot",
  chats: "chat",
  comments: "comment",
  daemons: "daemon",
  inbox: "inbox",
  invitations: "invite",
  issues: "issue",
  labels: "label",
  members: "member",
  pins: "pin",
  projects: "project",
  runtimes: "runtime",
  skills: "skill",
  squads: "squad",
  tasks: "task",
  tokens: "token",
  workspaces: "workspace",
  "notification-preferences": "notification",
  "cloud-billing": "billing",
  "cloud-runtime": "runtime",
  feedback: "platform",
  health: "platform",
  healthz: "platform",
  install: "lark",
  models: "runtime",
  "project-docs": "wiki",
  "project-knowledge": "memory",
  readyz: "platform",
  scheduler: "autopilot",
  shares: "share",
};

function main(): void {
  const golden = JSON.parse(readFileSync(GOLDEN_PATH, "utf8")) as { routes: string[] };
  const inventory = cliCommandInventory();
  const commands = Object.fromEntries(inventory.map((entry) => [entry.id, {
    command: `remi ${entry.path.join(" ")}`,
    aliases: entry.aliases.map((alias) => `remi ${alias.path.join(" ")}`),
    auth: [...entry.auth],
    capability: entry.capability,
    mutation: entry.mutation,
    output: [...entry.outputs],
    hidden: entry.hidden,
    ...(entry.id.startsWith("legacy.") ? { migration_status: "legacy_passthrough" as const } : { migration_status: "native" as const }),
    ...(entry.id === "legacy.multiremi" ? { internal: true } : {}),
  }]));
  const routes = Object.fromEntries(golden.routes.map((route) => [route, classifyRoute(route)]));
  const manifest: CliCapabilitiesManifest = {
    schema_version: 1,
    generated_from: "scripts/api-routes.golden.json",
    max_planned_routes: MAX_PLANNED_ROUTES,
    domains: DOMAINS,
    commands,
    aliases: {
      "remi multiremi": {
        command: "legacy.multiremi",
        deprecated_since: "0.3.0",
        replacement: "remi <command>",
        hidden: true,
      },
    },
    routes,
  };
  const errors = validateCliCapabilities(golden.routes, manifest, inventory);
  if (errors.length) throw new Error(errors.join("\n"));
  writeFileSync(MANIFEST_PATH, `${JSON.stringify(manifest, null, 2)}\n`);
  const runtimeManifest = cliRuntimeCapabilities(manifest);
  writeFileSync(
    RUNTIME_MANIFEST_PATH,
    `// Generated by scripts/generate-cli-capabilities.ts. Do not edit manually.\n`
      + `export const CLI_CAPABILITIES_RUNTIME = ${JSON.stringify(runtimeManifest, null, 2)} as const;\n`,
  );
  const report = cliCoverageReport(manifest);
  console.log(`CLI capabilities: ${report.mapped} mapped / ${report.exempt} exempt / ${report.missing} missing (${report.total} routes)`);
}

function classifyRoute(route: string): CliManifestRoute {
  if (route === "GET /api/cli/context" || route === "GET /api/cli/capabilities") {
    return { command: "context.get" };
  }
  const exempt = exemptRoute(route);
  if (exempt) return exempt;
  const { domain, command } = plannedCommand(route);
  return { planned_command: command, domain };
}

function exemptRoute(route: string): CliManifestRoute | null {
  const path = route.slice(route.indexOf(" ") + 1);
  const exempt = (category: CliExemptCategory, reason: string): CliManifestRoute => ({
    cli_exempt: true,
    category,
    reason,
  });
  if (path === "/ws" || path === "/api/daemon/ws" || path === "/api/realtime/ws") {
    return exempt("websocket_transport", "Long-lived WebSocket transport is outside the CLI command surface.");
  }
  if (path.startsWith("/api/daemon/") || /\/runtimes\/[^/]+\/heartbeat$/.test(path) || path === "/api/multiremi/scheduler/tick") {
    return exempt("daemon_internal_protocol", "Daemon heartbeat, claim, report, and execution protocol is machine-to-server traffic.");
  }
  if (path.startsWith("/api/webhooks/") || /\/(oauth|google)\/callback$/.test(path)) {
    return exempt("oauth_or_webhook_callback", "External provider callback is authenticated and invoked by the provider, not a user command.");
  }
  if (path.startsWith("/api/platform-updater/")) {
    return exempt("platform_updater_internal", "Platform updater callback is an internal deployment control-plane protocol.");
  }
  if (path === "/api/config" || path === "/api/contact-sales") {
    return exempt("pure_ui", "Browser bootstrap or presentation-only action has no meaningful CLI workflow.");
  }
  if (path === "/" || path === "/favicon.ico") {
    return exempt("public_bootstrap_asset", "Public service bootstrap asset has no user-side CLI operation.");
  }
  return null;
}

function plannedCommand(route: string): { domain: string; command: string } {
  const separator = route.indexOf(" ");
  const method = route.slice(0, separator);
  const path = route.slice(separator + 1);
  const segments = path.split("/").filter(Boolean);
  if (segments[0] === "api") segments.shift();
  if (segments[0] === "multiremi") segments.shift();
  let rawDomain = segments[0] ?? "platform";
  if (rawDomain === "auth") rawDomain = "context";
  if (rawDomain === "me") rawDomain = "member";
  if (rawDomain === "remi" || rawDomain === "install.sh") rawDomain = "platform";
  if (rawDomain === "cli-token") rawDomain = "token";
  if (rawDomain === "upload-file") rawDomain = "attachment";
  if (rawDomain === "lark") rawDomain = "lark";
  const domain = DOMAIN_ALIASES[rawDomain] ?? rawDomain;
  const staticTail = [...segments].reverse().find((segment) => !segment.startsWith(":")) ?? rawDomain;
  const collection = segments.length <= 1 || (segments.length === 2 && segments[1] === "search");
  let action = method === "GET" ? (collection ? "list" : "get")
    : method === "DELETE" ? "delete"
      : method === "PATCH" || method === "PUT" ? "update"
        : collection ? "create" : normalizeAction(staticTail);
  if (staticTail === "search") action = "search";
  if (path === "/health" || path === "/healthz" || path === "/readyz"
    || path === "/health/realtime" || path === "/api/multiremi/health") action = "status";
  if (staticTail === "archive" || staticTail === "restore" || staticTail === "verify" || staticTail === "retry"
    || staticTail === "cancel" || staticTail === "respond" || staticTail === "checkout" || staticTail === "trigger") {
    action = staticTail;
  }
  return { domain, command: `${domain}.${action}` };
}

function normalizeAction(value: string): string {
  return value.replace(/[^a-zA-Z0-9]+/g, "_").replace(/^_+|_+$/g, "") || "update";
}

main();
