#!/usr/bin/env bun

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { cliCommandInventory } from "../apps/remi/cli/index.js";
import {
  cliCoverageReport,
  cliRuntimeCapabilities,
  type CliCapabilitiesManifest,
  type CliExemptCategory,
  type CliManifestRoute,
  validateCliCapabilities,
} from "./cli-capabilities.js";

const ROOT = resolve(import.meta.dir, "..");
const GOLDEN_PATH = resolve(ROOT, "scripts/api-routes.golden.json");
const MANIFEST_PATH = resolve(ROOT, "cli-capabilities.json");
const RUNTIME_MANIFEST_PATH = resolve(ROOT, "packages/server/src/api/cli-capabilities-generated.ts");
const MAX_PLANNED_ROUTES = 417;

const DOMAINS = [
  "context", "workspace", "member", "invite", "token",
  "project", "repo", "memory", "wiki",
  "issue", "comment", "session", "share", "label", "attachment",
  "chat", "task",
  "agent", "squad", "skill", "plugin",
  "runtime", "daemon", "autopilot", "scm",
  "inbox", "notification", "pin", "dashboard", "platform", "billing", "lark",
];

const DOMAIN_ALIASES: Record<string, string> = {
  "agent-plugins": "plugin",
  "agent-templates": "agent",
  "agent-activity-30d": "dashboard",
  "agent-run-counts": "dashboard",
  "agent-task-snapshot": "dashboard",
  "assignee-frequency": "dashboard",
  agents: "agent",
  attachments: "attachment",
  autopilots: "autopilot",
  chats: "chat",
  comments: "comment",
  daemons: "daemon",
  inbox: "inbox",
  invitations: "invite",
  issues: "issue",
  labels: "label",
  members: "member",
  pins: "pin",
  projects: "project",
  runtimes: "runtime",
  skills: "skill",
  squads: "squad",
  tasks: "task",
  tokens: "token",
  workspaces: "workspace",
  "notification-preferences": "notification",
  "cloud-billing": "billing",
  "cloud-runtime": "runtime",
  feedback: "platform",
  health: "platform",
  healthz: "platform",
  install: "lark",
  models: "runtime",
  "project-docs": "wiki",
  "project-knowledge": "memory",
  readyz: "platform",
  scheduler: "autopilot",
  shares: "share",
};

function main(): void {
  const golden = JSON.parse(readFileSync(GOLDEN_PATH, "utf8")) as { routes: string[] };
  const inventory = cliCommandInventory();
  const commands = Object.fromEntries(inventory.map((entry) => [entry.id, {
    command: `remi ${entry.path.join(" ")}`,
    aliases: entry.aliases.map((alias) => `remi ${alias.path.join(" ")}`),
    auth: [...entry.auth],
    capability: entry.capability,
    mutation: entry.mutation,
    output: [...entry.outputs],
    hidden: entry.hidden,
    ...(entry.id.startsWith("legacy.") ? { migration_status: "legacy_passthrough" as const } : { migration_status: "native" as const }),
    ...(entry.id === "legacy.multiremi" ? { internal: true } : {}),
  }]));
  const routes = Object.fromEntries(golden.routes.map((route) => [route, classifyRoute(route)]));
  const manifest: CliCapabilitiesManifest = {
    schema_version: 1,
    generated_from: "scripts/api-routes.golden.json",
    max_planned_routes: MAX_PLANNED_ROUTES,
    domains: DOMAINS,
    commands,
    aliases: {
      ...Object.fromEntries(inventory.flatMap((entry) => entry.aliases
        .filter((alias) => alias.deprecatedSince)
        .map((alias) => [`remi ${alias.path.join(" ")}`, {
          command: entry.id,
          deprecated_since: alias.deprecatedSince!,
          replacement: alias.replacement ?? `remi ${entry.path.join(" ")}`,
          hidden: Boolean(alias.hidden),
        }]))),
      "remi multiremi": {
        command: "legacy.multiremi",
        deprecated_since: "0.3.0",
        replacement: "remi <command>",
        hidden: true,
      },
    },
    routes,
  };
  const errors = validateCliCapabilities(golden.routes, manifest, inventory);
  if (errors.length) throw new Error(errors.join("\n"));
  writeFileSync(MANIFEST_PATH, `${JSON.stringify(manifest, null, 2)}\n`);
  const runtimeManifest = cliRuntimeCapabilities(manifest);
  writeFileSync(
    RUNTIME_MANIFEST_PATH,
    `// Generated by scripts/generate-cli-capabilities.ts. Do not edit manually.\n`
      + `export const CLI_CAPABILITIES_RUNTIME = ${JSON.stringify(runtimeManifest, null, 2)} as const;\n`,
  );
  const report = cliCoverageReport(manifest);
  console.log(`CLI capabilities: ${report.mapped} mapped / ${report.exempt} exempt / ${report.missing} missing (${report.total} routes)`);
}

function classifyRoute(route: string): CliManifestRoute {
  const mapped = mappedResourceCommand(route);
  if (mapped) return { command: mapped };
  const exempt = exemptRoute(route);
  if (exempt) return exempt;
  const { domain, command } = plannedCommand(route);
  return { planned_command: command, domain };
}

function mappedResourceCommand(route: string): string | null {
  const exact: Record<string, string> = {
    "GET /api/cli/context": "context.get",
    "GET /api/cli/capabilities": "context.get",
    "GET /api/workspaces": "workspace.list",
    "POST /api/workspaces": "workspace.create",
    "GET /api/invitations": "invite.list",
    "GET /api/me": "member.get",
    "PATCH /api/me": "member.update",
    "PATCH /api/me/onboarding": "member.onboarding.update",
    "POST /api/me/onboarding/complete": "member.onboarding.complete",
    "POST /api/me/onboarding/cloud-waitlist": "member.onboarding.cloud-waitlist",
    "POST /api/me/onboarding/runtime-bootstrap": "member.onboarding.runtime-bootstrap",
    "POST /api/me/onboarding/no-runtime-bootstrap": "member.onboarding.no-runtime-bootstrap",
    "GET /api/multiremi/members": "member.list",
    "POST /api/multiremi/members": "member.create",
    "GET /api/tokens": "token.list",
    "POST /api/tokens": "token.create",
    "POST /api/tokens/current/renew": "token.renew",
    "GET /api/multiremi/tokens": "token.list",
    "POST /api/multiremi/tokens": "token.create",
    "POST /api/cli-token": "token.create",
    "GET /api/projects": "project.list",
    "POST /api/projects": "project.create",
    "GET /api/projects/search": "project.search",
    "GET /api/multiremi/projects": "project.list",
    "POST /api/multiremi/projects": "project.create",
    "GET /api/multiremi/projects/search": "project.search",
    "GET /api/project-docs": "memory.list",
    "GET /api/project-knowledge/migration": "memory.migration.status",
    "POST /api/project-knowledge/migration/backfill": "memory.migration.backfill",
    "POST /api/project-knowledge/migration/verify": "memory.migration.verify",
    "POST /api/project-knowledge/migration/retry-failed": "memory.migration.retry",
  };
  if (exact[route]) return exact[route]!;
  const rules: Array<[RegExp, string]> = [
    [/^GET \/api\/workspaces\/:id$/, "workspace.get"],
    [/^(?:PUT|PATCH) \/api\/workspaces\/:id$/, "workspace.update"],
    [/^DELETE \/api\/workspaces\/:id$/, "workspace.delete"],
    [/^POST \/api\/workspaces\/:id\/leave$/, "workspace.leave"],
    [/^GET \/api\/workspaces\/:id\/env$/, "workspace.env.get"],
    [/^PUT \/api\/workspaces\/:id\/env$/, "workspace.env.update"],
    [/^GET \/api\/workspaces\/:id\/ssh-mesh$/, "workspace.ssh-mesh.get"],
    [/^PUT \/api\/workspaces\/:id\/ssh-mesh$/, "workspace.ssh-mesh.update"],
    [/^POST \/api\/workspaces\/:id\/ssh-mesh\/rotate$/, "workspace.ssh-mesh.rotate"],
    [/^POST \/api\/workspaces\/:id\/ssh-mesh\/test$/, "workspace.ssh-mesh.test"],
    [/^GET \/api\/workspaces\/:id\/relay-config$/, "workspace.relay.get"],
    [/^PUT \/api\/workspaces\/:id\/relay-config\/discovery$/, "workspace.relay.discovery"],
    [/^PUT \/api\/workspaces\/:id\/relay-config\/:engine$/, "workspace.relay.update"],
    [/^POST \/api\/workspaces\/:id\/relay-config\/:engine\/reveal$/, "workspace.relay.reveal"],
    [/^GET \/api\/workspaces\/:id\/members$/, "member.list"],
    [/^PATCH \/api\/workspaces\/:id\/members\/:memberId$/, "member.update"],
    [/^DELETE \/api\/workspaces\/:id\/members\/:memberId$/, "member.delete"],
    [/^POST \/api\/workspaces\/:id\/members$/, "invite.create"],
    [/^GET \/api\/multiremi\/members\/:id$/, "member.get"],
    [/^PATCH \/api\/multiremi\/members\/:id$/, "member.update"],
    [/^DELETE \/api\/multiremi\/members\/:id$/, "member.delete"],
    [/^GET \/api\/workspaces\/:id\/invitations$/, "invite.list"],
    [/^DELETE \/api\/workspaces\/:id\/invitations\/:invitationId$/, "invite.revoke"],
    [/^GET \/api\/invitations\/:id$/, "invite.get"],
    [/^POST \/api\/invitations\/:id\/accept$/, "invite.accept"],
    [/^POST \/api\/invitations\/:id\/decline$/, "invite.decline"],
    [/^DELETE \/api\/(?:multiremi\/)?tokens\/:id$/, "token.delete"],
    [/^GET \/api\/(?:multiremi\/)?projects\/:id$/, "project.get"],
    [/^(?:PUT|PATCH) \/api\/(?:multiremi\/)?projects\/:id$/, "project.update"],
    [/^DELETE \/api\/(?:multiremi\/)?projects\/:id$/, "project.archive"],
    [/^POST \/api\/(?:multiremi\/)?projects\/:id\/restore$/, "project.restore"],
    [/^GET \/api\/(?:multiremi\/)?projects\/:id\/resources$/, "project.resource.list"],
    [/^POST \/api\/(?:multiremi\/)?projects\/:id\/resources$/, "project.resource.create"],
    [/^(?:PUT|PATCH) \/api\/(?:multiremi\/)?projects\/:id\/resources\/:resourceId$/, "project.resource.update"],
    [/^DELETE \/api\/(?:multiremi\/)?projects\/:id\/resources\/:resourceId$/, "project.resource.delete"],
    [/^GET \/api\/projects\/:id\/docs$/, "memory.list"],
    [/^POST \/api\/projects\/:id\/docs$/, "memory.create"],
    [/^GET \/api\/projects\/:id\/docs\/:ref$/, "memory.get"],
    [/^PUT \/api\/projects\/:id\/docs\/:ref$/, "memory.update"],
    [/^DELETE \/api\/projects\/:id\/docs\/:ref$/, "memory.delete"],
    [/^GET \/api\/projects\/:id\/docs\/:ref\/revisions$/, "wiki.revisions"],
    [/^GET \/api\/projects\/:id\/docs\/:ref\/backlinks$/, "memory.backlinks"],
    [/^GET \/api\/projects\/:id\/knowledge\/recall$/, "memory.search"],
    [/^GET \/api\/workspaces\/:id\/repos$/, "repo.list"],
    [/^POST \/api\/workspaces\/:id\/repos\/inspect$/, "repo.inspect"],
    [/^POST \/api\/workspaces\/:id\/repos$/, "repo.create"],
    [/^PATCH \/api\/workspaces\/:id\/repos\/:repositoryId$/, "repo.update"],
    [/^DELETE \/api\/workspaces\/:id\/repos\/:repositoryId$/, "repo.delete"],
  ];
  return rules.find(([pattern]) => pattern.test(route))?.[1] ?? null;
}

function exemptRoute(route: string): CliManifestRoute | null {
  const path = route.slice(route.indexOf(" ") + 1);
  const exempt = (category: CliExemptCategory, reason: string): CliManifestRoute => ({
    cli_exempt: true,
    category,
    reason,
  });
  if (path === "/ws" || path === "/api/daemon/ws" || path === "/api/realtime/ws") {
    return exempt("websocket_transport", "Long-lived WebSocket transport is outside the CLI command surface.");
  }
  if (path.startsWith("/api/daemon/") || /\/runtimes\/[^/]+\/heartbeat$/.test(path) || path === "/api/multiremi/scheduler/tick") {
    return exempt("daemon_internal_protocol", "Daemon heartbeat, claim, report, and execution protocol is machine-to-server traffic.");
  }
  if (path.startsWith("/api/webhooks/") || /\/(oauth|google|lark)\/callback$/.test(path)) {
    return exempt("oauth_or_webhook_callback", "External provider callback is authenticated and invoked by the provider, not a user command.");
  }
  if (path.startsWith("/api/platform-updater/")) {
    return exempt("platform_updater_internal", "Platform updater callback is an internal deployment control-plane protocol.");
  }
  if (path === "/api/config" || path === "/api/contact-sales") {
    return exempt("pure_ui", "Browser bootstrap or presentation-only action has no meaningful CLI workflow.");
  }
  if (path === "/" || path === "/favicon.ico") {
    return exempt("public_bootstrap_asset", "Public service bootstrap asset has no user-side CLI operation.");
  }
  return null;
}

function plannedCommand(route: string): { domain: string; command: string } {
  const separator = route.indexOf(" ");
  const method = route.slice(0, separator);
  const path = route.slice(separator + 1);
  const segments = path.split("/").filter(Boolean);
  if (segments[0] === "api") segments.shift();
  if (segments[0] === "multiremi") segments.shift();
  let rawDomain = segments[0] ?? "platform";
  if (rawDomain === "workspaces" && segments.includes("scm")) rawDomain = "scm";
  else if (rawDomain === "workspaces" && segments.includes("lark")) rawDomain = "lark";
  else if (rawDomain === "workspaces" && segments.includes("session-archive")) rawDomain = "session";
  if (rawDomain === "auth") rawDomain = "context";
  if (rawDomain === "me") rawDomain = "member";
  if (rawDomain === "remi" || rawDomain === "install.sh") rawDomain = "platform";
  if (rawDomain === "cli-token") rawDomain = "token";
  if (rawDomain === "upload-file") rawDomain = "attachment";
  if (rawDomain === "lark") rawDomain = "lark";
  const domain = DOMAIN_ALIASES[rawDomain] ?? rawDomain;
  const staticTail = [...segments].reverse().find((segment) => !segment.startsWith(":")) ?? rawDomain;
  const collection = segments.length <= 1 || (segments.length === 2 && segments[1] === "search");
  let action = method === "GET" ? (collection ? "list" : "get")
    : method === "DELETE" ? "delete"
      : method === "PATCH" || method === "PUT" ? "update"
        : collection ? "create" : normalizeAction(staticTail);
  if (staticTail === "search") action = "search";
  if (path === "/health" || path === "/healthz" || path === "/readyz"
    || path === "/health/realtime" || path === "/api/multiremi/health") action = "status";
  if (staticTail === "archive" || staticTail === "restore" || staticTail === "verify" || staticTail === "retry"
    || staticTail === "cancel" || staticTail === "respond" || staticTail === "checkout" || staticTail === "trigger") {
    action = staticTail;
  }
  return { domain, command: `${domain}.${action}` };
}

function normalizeAction(value: string): string {
  return value.replace(/[^a-zA-Z0-9]+/g, "_").replace(/^_+|_+$/g, "") || "update";
}

main();
