/**
 * PM2 ecosystem config generator and service management.
 *
 * Reads [[services]] from remi.toml and generates PM2 ecosystem config.
 * Remi core is always included as the first app.
 */

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { execSync } from "node:child_process";
import { homedir } from "node:os";
import { join, resolve } from "node:path";
import type { RemiConfig } from "./config.js";
import { createLogger } from "./logger.js";

const log = createLogger("pm2");

const REMI_ROOT = resolve(import.meta.dir, "..");
const ECOSYSTEM_PATH = join(homedir(), ".remi", "ecosystem.config.cjs");

export function getEcosystemPath(): string {
  return ECOSYSTEM_PATH;
}

/** Generate PM2 ecosystem config content from remi.toml services. */
export function generateEcosystem(config: RemiConfig): string {
  const apps: Record<string, unknown>[] = [
    {
      name: "remi",
      script: "src/main.ts",
      args: "serve",
      interpreter: "bun",
      cwd: REMI_ROOT,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
    },
  ];

  for (const svc of config.services) {
    if (!svc.enabled || !svc.script) continue;
    const app: Record<string, unknown> = {
      name: svc.name,
      script: svc.script,
      interpreter: svc.interpreter || "bun",
      cwd: svc.cwd,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 2000,
    };
    if (svc.args.length) app.args = svc.args.join(" ");
    if (svc.port) app.env = { PORT: svc.port };
    apps.push(app);
  }

  return `// Auto-generated by Remi — do not edit manually.\n` +
    `module.exports = { apps: ${JSON.stringify(apps, null, 2)} };\n`;
}

/** Write ecosystem config to ~/.remi/ecosystem.config.cjs. */
export function writeEcosystem(config: RemiConfig): string {
  const dir = join(homedir(), ".remi");
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  writeFileSync(ECOSYSTEM_PATH, generateEcosystem(config));
  return ECOSYSTEM_PATH;
}

/** Run build commands for all services that have them. */
export function runBuildsSync(config: RemiConfig): void {
  for (const svc of config.services) {
    if (!svc.enabled || !svc.build) continue;
    log.info(`Building "${svc.name}": ${svc.build}`);
    try {
      execSync(svc.build, { cwd: svc.cwd, stdio: "inherit", timeout: 120_000 });
      log.info(`Build "${svc.name}" succeeded.`);
    } catch (e) {
      log.error(`Build "${svc.name}" failed:`, e);
    }
  }
}

/** Full PM2 start: generate config → run builds → pm2 start. */
export function pm2Start(config: RemiConfig): void {
  runBuildsSync(config);
  const path = writeEcosystem(config);

  log.info("Starting all services with PM2...");
  try {
    execSync(`pm2 start ${path}`, { stdio: "inherit" });
    execSync("pm2 save", { stdio: "inherit" });
    log.info("All services started. Run `pm2 status` to check.");
  } catch (e) {
    log.error("PM2 start failed:", e);
    process.exit(1);
  }
}

/** Stop all PM2-managed services. */
export function pm2Stop(): void {
  try {
    execSync("pm2 stop all", { stdio: "inherit" });
    log.info("All services stopped.");
  } catch (e) {
    log.error("PM2 stop failed:", e);
  }
}
